### ISSUE TITLE
Problems with Meerkat success and notification messages

### ISSUE THREAD

**Issue by jeffwhitfield** [Stillat/meerkat-v1hub#10]
I’m having a heck of a time debugging a few issues with Meerkat. Here’s what I’m running into issues with…

First, for some reason, whenever a person posts a comment, the success message never shows. I know it’s working well for my Contact form…but not the Meerkat form for some reason. Here’s a gist of my template for the blog post:

https://gist.github.com/jeffwhitfield/06f3c118aef0b78d4cb247b7ebd51b55

You can see the comment form live for any post on my blog: https://velonut.com

The other problem is that email notifications for a new comment never get sent. Again, works for my Contact page…just not for Meerkat.

Any idea on why this is happening just for Meerkat? :P

**Comment by JohnathonKoster** [comment]
Resolved, and released as v 1.5.5 (available in Releases and in the Statamic Marketplace)
