### ISSUE TITLE
Error when trying to implement "Reply To" Link

### ISSUE THREAD

**Issue by norrelund** [Stillat/meerkat-v1hub#13]
When I try to implement the "Reply To" Link i get this error.

ErrorException in MeerkatController.php line 376:
count(): Parameter must be an array or an object that implements Countable

This happens after I submit the reply to form. I followed the documentation regarding "Allowing Visitors to Reply to Each Other". And as far as I can see I did as described, so not quite sure how to proceed here. 

![code](https://user-images.githubusercontent.com/30465262/66818785-22101180-ef3e-11e9-8d2f-0293300f4a9b.png)

I'm using version 1.5.5.

**Comment by JohnathonKoster** [comment]
Fixed in v1.5.61 (update in Statamic Marketplace)
