### ISSUE TITLE
CP - JS error in ReplyTo or Edit 

### ISSUE THREAD

**Issue by luizboaretto** [Stillat/meerkat-v1hub#14]
I can't reply to or edit comments on the CP.

```console
TypeError: _.findWhere is not a functionMeerkatStreamListing.js:492
    replyToComment MeerkatStreamListing.js:492
    b VueJS
    call DossierTable.js:290
    b VueJS
    anonymous vendor.js:3
    VueJS 2
```
Statamic version: 2.11.15
Meerkat version: 1.5.5

**Comment by jeremydouglas** [comment]
I have the same results. 

This is the error that shows in Chrome dev tools:

`xhr.js:42 POST http://deboss-garage-api.test/cp/addons/meerkat/postSocialize 400 (Bad Request)`

**Comment by JohnathonKoster** [comment]
I will be improving the error messages in the CP in 1.5.7 (working to have released ~Jun 29th).

This can happen if the form validation fails (by default the comment required length is set to a minimum of 5 characters).

**Comment by JohnathonKoster** [comment]
@luizboaretto @jeremydouglas 

The Control Panel now better reflects errors and their actual messages as of v1.5.71 (this update  also resolves the findWhere bug with reply/edit) and can be downloaded from the Statamic Marketplace https://statamic.com/marketplace/addons/meerkat
