### ISSUE TITLE
Action alerts false-positive

### ISSUE THREAD

**Issue by luizboaretto** [Stillat/meerkat-v1hub#15]
When Approve, Unapprove, Mark as Spam always return failed alerts but actions are returned as success.

------

Could Not Mark Comment as Spam
There was a problem marking the comment as spam.

Response: `{"success":true,"marked":[1573682365],"errorMessage":null}`

-----

Could Not Mark Comment as Not Spam
There was a problem marking the comment as not spam.

Response: `{"success":true,"marked":[1573682365],"errorMessage":null}`

**Comment by JohnathonKoster** [comment]
@luizboaretto 

The response structure of these two API calls have been changed in v1.5.70 to better indicate what is going on, as well as enable the improved error display:

```
comment_saved: true                           Indicates if the comment was saved locally.
errorMessage: ["Akismet: ERROR"]      A list of error messages, with provider and the ERROR.
marked: [1592709712]                         A list of comment IDs that were changed or reported.
specimen_sent: false                            Indicates if comment data was sent to third-party services.
submit_success: false                           Indicates if any third-party services failed.
```

v1.5.70 is now available on the Statamic Marketplace: https://statamic.com/marketplace/addons/meerkat
