### ISSUE TITLE
Getting total number of comments including replies

### ISSUE THREAD

**Issue by jeffwhitfield** [Stillat/meerkat-v1hub#16]
I'm trying to write a simple Addon that gets the total number of comments including replies. Got it so that it can return the total number of comments...but it doesn't include replies in that. How would I use the API to calculate the number of total replies and add it to that number? Thx in advance!  :D

**Comment by JohnathonKoster** [comment]
@jeffwhitfield 

For previous versions of Meerkat, you can retrieve the total number of comments like so by utilizing the comment Manager class. The following example demonstrates how to do this from within a site Tags helper:

```php
<?php

namespace Statamic\SiteHelpers;

use Statamic\Extend\Tags as AbstractTags;

class Tags extends AbstractTags
{
    public function commentCount()
    {
        $postId = array_get($this->context, 'id');
        $commentCount = 0;

        if ($postId !== null) {
            // Create instance of Stream Manager
            $manager = app(\Statamic\Addons\Meerkat\Comments\Manager::class);

            $items = $manager->getStreamComments($postId, true);
            $commentCount = $items->filter(function ($comment) {
                // Filters to just published comments.
                return $comment->published();
            })->count();
        }

        return $commentCount;
    }
}
```

The signature of the `getStreamComments` method is:

```php
public function getStreamComments($stream, $flatList = false)
```

`$stream` should be the ID of the context you'd like to get the comments for. When `true` is supplied for `$flatList`, it will return all the comments as a flat-array (no nesting).

Starting with Meerkat v1.5.64 (now available in the Statamic Marketplace), a new API helper method was added. The previous example can now be rewritten like so:

```php
<?php

namespace Statamic\SiteHelpers;

use Statamic\Extend\Tags as AbstractTags;

class Tags extends AbstractTags
{
    public function commentCount()
    {
        $postId = array_get($this->context, 'id');

        return $this->api('Meerkat')->getPublishedCommentCount($postId);
    }
}
```

If you have any other issues/questions, please create a new ticket!
