### ISSUE TITLE
Google reCaptcha not working

### ISSUE THREAD

**Issue by jeffwhitfield** [Stillat/meerkat-v1hub#17]
Just noticed this today after getting a bunch of spam comments. Seems that the Google reCaptcha add-on doesn't work:

https://statamic.com/marketplace/addons/google-recaptcha

Don't think it's picking up the submissions at all. How would I go about adding on reCaptcha or even hCaptcha to this?

**Comment by jeffwhitfield** [comment]
Looping back around to this one. Any way we can get this working? I know you're busy working on v2 for Statamic v3 which is awesome. However, is there an interim fix we might be able to implement? Reason I ask is that I'm getting quite a bit of comment spam. :P

**Comment by JohnathonKoster** [comment]
@jeffwhitfield  This support is now available in v1.5.63, and can be downloaded from the Statamic Marketplace

Authenticated and Control Panel users will bypass captcha validation by default (to prevent errors when submitting replies via. the Control Panel). This behavior can be changed by adding a `captcha_auth_bypass` configuration entry to `settings/addons/meerkat.yaml` and setting it's value to `false`.
