### ISSUE TITLE
Control Panel: Reply and Edit buttons not working

### ISSUE THREAD

**Issue by jeffwhitfield** [Stillat/meerkat-v1hub#20]
Unfortunately, recent updates appear to have created a few more bugs. Will document them in new tickets as best as possible. Oh, the fun of software development! :P 

While in the CP, if I click on an Edit or Reply button, nothing happens. Looking at the Console, it appears the problem is in the `MeerkatStreamListing.js` file with both actions resulting in a `item is not defined` error.

**Comment by JohnathonKoster** [comment]
@jeffwhitfield  I have been able to replicate this and will have it fixed in a 1.5.73 patch today

Relates to #21

**Comment by JohnathonKoster** [comment]
Corrected in patch 1.5.73, and is available in the Statamic Marketplace: https://statamic.com/marketplace/addons/meerkat

**Comment by jeffwhitfield** [comment]
You rock!  👯
