### ISSUE TITLE
Control Panel: Could Not Approve Comment

### ISSUE THREAD

**Issue by jeffwhitfield** [Stillat/meerkat-v1hub#21]
Whenever a new reply comes in and I go into the CP to approve it, click on the Approve button results in a "Could Not Approve Comment" error. However, after a refresh, the comment appears to have been approved anyways so...false error? :P

**Comment by JohnathonKoster** [comment]
@jeffwhitfield  I have been able to replicate this and will have it fixed in a 1.5.73 patch today :)

**Comment by jeffwhitfield** [comment]
Coolness! Thx @JohnathonKoster! 

BTW, I know seeing a bunch of new issues after fixing previous issues isn't fun. Sorry about all the new issue posts. :P

**Comment by JohnathonKoster** [comment]
@jeffwhitfield No worries! I believe I've identified where the build tool failed (on outputting updated assets), and will work to have that resolved on my end as well

**Comment by JohnathonKoster** [comment]
Corrected in patch 1.5.73, and is available in the Statamic Marketplace: https://statamic.com/marketplace/addons/meerkat

**Comment by jeffwhitfield** [comment]
You rock!  🍰
