### ISSUE TITLE
Replies to a comment being saved as top-level comment

### ISSUE THREAD

**Issue by jeffwhitfield** [Stillat/meerkat-v1hub#22]
While testing a few other issues, I noticed that any replies to a comment are being saved as a top-level comment rather than as a reply. Definitely worked before the most recent updates and nothing else in my code has changed so...doh!

**Comment by JohnathonKoster** [comment]
Will do some digging on this and find where the regression occurred, and hope to have it available in the 1.5.73 patch :)

**Comment by JohnathonKoster** [comment]
@jeffwhitfield  Can replicate; will be part of 1.5.73 patch here in about 20 minutes

**Comment by JohnathonKoster** [comment]
Corrected in patch 1.5.73, and is available in the Statamic Marketplace: https://statamic.com/marketplace/addons/meerkat

**Comment by jeffwhitfield** [comment]
Oh and...uhh...you rock!  🏎️
