### ISSUE TITLE
reCaptcha Integration and Replies

### ISSUE THREAD

**Issue by JohnathonKoster** [Stillat/meerkat-v1hub#24]
Using the replies-to JavaScript and the reCaptcha plugin prevents comments from being submitted:

* Need to detect captcha integrations and create them in the Replies form as well so that valid data can be submitted

**Comment by jeffwhitfield** [comment]
Yeah, noticed that too myself. Kind of a weird thing.

**Comment by JohnathonKoster** [comment]
@jeffwhitfield 

Should be resolved in 1.5.74, which is now available in the Statamic Marketplace (https://statamic.com/marketplace/addons/meerkat)

@lachieh Tagging you in this as well in case you've ran into this :)
