### ISSUE TITLE
Statamic 3 Migration

### ISSUE THREAD

**Issue by JohnathonKoster** [Stillat/meerkat-v1hub#26]
Port of 1.5.80 Meerkat for Statamic 2 to Statamic v3 (task list WIP)

> Host: Statamic 2, Statamic 3, etc.
> Pre-Host: Meerkat Core and other internal processes, should be capable of not relying on Host parsers

- [x] Updated to Statamic 3.0.0-beta.44
- [x] Migrate to Linux systems development
- [x] Milestone 1: Statamic 3 Addon Base Complete!  🎉🎉🎉🎉
- [x] Milestone 2: Meerkat Core Integrated (done enough for Statamic 3 specific stuff to start)  🎉🎉🎉🎉
  - [x] Thread Manager Base Complete! 🎉🎉🎉🎉
  - [x] Comment Structure Migrator Complete! 🎉🎉🎉🎉
- [x] Milestone 3: Templating Systems Integrated 
  - [x] Recursive Comment Thread Rendering Implemented  🎉🎉🎉🎉
  - [x] Grouped Rendering
  - [x] Pagianted Rendering
  - [x] Grouped and Paginated Rendering
  - [x] Flat List Rendering
- [ ] Milestone 4: Form Life-cycle Integrated (in progress)
  - [ ] Check for Spam After new submissions
  - [ ] Delayed Response Execution of Post-Save/Reply hooks
- [ ] Milestone 5: Control Panel

## Addon Base

- [x] Get Basic Addon Registering
- [x] Create Route Structure
- [x] `EmitsEvents` Concern
- [x] `UsesConfig` Concern
- [x] `UsesTranslations` Concern
- [x] Provide Backwards Compatibility with Meerkat for Statamic 2 Addon Endpoints
- [x] Create and wire `resources` directory (views)
- [x] Base Antlers Tag Integration
- [x] Resolve Statamic `Addon` Instance for Current Addon
- [x] Resolve Addon Installation Directory at Runtime
- [x] Research Possibility of Multiple Service Providers for Organization of Addon Services
  - [x] Allow for a Service Provider to only boot/register depending on runtime context
    - [x] Control Panel
    - [x] Web
    - [x] CLI

## Control Panel
- [x] Create a base view for addon
- [x] Add custom Statamic 3 menu item
- [x] Custom Addon Icon(s) in Statamic 3 menu
- [x] Detect CP Requests
- [x] Begin Porting Suricatta User Interface
  - [x] Basic Visual Elements Displaying
  - [x] Meerkat Thread - In progress
  - [ ] Meerkat Thread Actions
  - [ ] Meerkat Thread Bulk Actions
  - [ ] Meerkat Avatar Drivers
    - [x] Back-end Initials Driver
    - [x] Back-end Gravatar Driver
- [x] Pull in Meerkat Core-JS Dependency
  - [ ] Data Models and Structures
  - [ ] Data Access Layers
  - [ ] Common Meerkat Utilities
- [x] Provide Meerkat Blueprint Editor (only supporting Meerkat for Statamic 3 after blueprint refactors)
- [x] Add Meerkat to "Other" Blueprint Category in CP -> Blueprints

*Note: Suricatta includes UI features not available in 1.5.80. These will be removed for the initial port.*

## Forms

- [x] Refactored Away From Directly Using Statamic Forms
- [x] Allow Users to Define Fields and Validation Rules Using Blueprints
- [x] Base Form Handler
- [x] Request Input Validation
- [x] Honeypot Implementation
- [x] Raise Native Statamic Events (things like reCaptcha, etc.) - may require a "mocked" Submission for API compatibility

## Comment Submissions

- [x] Persist New Comments
- [x] Persist Replies

## Exporters

- [ ] CSV
- [ ] JSON
- [ ] ???

## Translations - Control Panel and Error Messages

- [x] Resolve translations from resources (server side)
- [x] Resolve translations from resources (front end)
- [x] Ensure that fallback locale translations are utilized when current locale does not have a translation in the Statamic Control Panel
- [ ] English
- [ ] French
- [ ] German
- [ ] Italian

## Integration

- [x] Allow the Thread Storage Driver to be configurable
- [x] Allow the Comment Storage Driver to be configurable
- [x] Guard against missing storage drivers, incorrect configuration, etc. and fallback to local drivers when necessary
- [x] Implement Meerkat Core Identities
- [x] Implement Meerkat Core Identity Manager
- [x] Non-Transient Identities
- [x] Transient Identities
- [x] Permissions Management
- [ ] Laravel Policies for Permissible Actions
- [x] Settings Management - Users can now configure Meerkat through the `config/` directory. Will revisit at a later date to determine best way to allow for UI management of settings
- [ ] Detect Meerkat-capable Requests
- [x] Research Statamic 3 Form Lifecycle (event seems to be removed and moved to dedicated runCreating event)
- [x] Investigate Statamic 3 Native Events
- [x] Validators, Error Codes, and Solutions Provider
  - [x] Integrate Error Codes from Meerkat Core
  - [x] Integrate System(s) Validators from Meerkat Core
  - [x] Implement Error Code and Context System from Meerkat Core
  - [x] Implement Solutions Provider

## Caches

- [x] Identity Resolver
- [x] Context Resolver
- [x] Thread Resolver
- [x] Permissions Resolver

## Antlers Tags

- [x] Meerkat Version Tag
- [x] Meerkat Form
- [x] Reply Form
- [x] Responses
  - [x] Recursive Thread Rendering
  - [x] Flat-List Thread Rendering
  - [x] Grouped Thread Rendering (group_by_date)
  - [x] Paginated Thread Rendering
  - [x] Paginated *and* Grouped Thread Rendering
- [x] Replies To JavaScript Tag
- [x] Comment Count - In progress
- [X] Research recursive rendering in Statamic v3 (remains fairly consistent with current behavior, will need to look into new Concerns pattern utilized in /cms tags)

Note: Meerkat 2 for Statamic 3 has an automatic memory exhaustion protection.

### Example of Recrusive

Templates should always check `has_replies` when recursively displaying comments:

```html
{{ meerkat:responses as="comments" }}

    <ul>
    {{ comments }}
        <li>
            {{ id }} - {{ content_raw }}
    
            {{ if has_replies }}
            <ul>{{ *recursive comments* }}</ul>
            {{ /if }}
        </li>
    
    {{ /comments }}
    </ul>

{{ /meerkat:responses }}
```

### Example of Flat List Rendering

```html
{{ meerkat:responses include_unapproved="true" flat="true" }}

<ul class="list-none mx-auto mt-5 p-5">
    {{ comments }}
    <li class="relative flex w-full flow-root">
        <img src="https://picsum.photos/id/684/600/400" alt=""
             class="h-12 w-12 mt-1 border-gray-500 rounded-full border-4">

        <div class="relative">
            <p class="block font-bold p-3 lg:text-lg">{{ author.name }} says:</p>
            <p class="block static text-justify text-xs sm:text-sm lg:text-lg p-3">{{ content }}</p>

            <ul class="list-none p-3">
                <li><a href="#" data-meerkat-form="reply" data-meerkat-reply-to="{{ id }}">Reply</a></li>
            </ul>

        </div>
    </li>
    {{ /comments }}
</ul>

{{ /meerkat:responses }}

```

### Example of Grouped Rendering

```html
{{ meerkat:responses group_by_date="Y m, d" }}


{{ date_groups }}
<h2>Group: {{ date_group }}</h2>

<ul>
    {{ comments }}
    <li class="relative flex w-full flow-root">
        <img src="https://picsum.photos/id/684/600/400" alt=""
             class="h-12 w-12 mt-1 border-gray-500 rounded-full border-4">

        <div class="relative">
            <p class="block font-bold p-3 lg:text-lg">{{ author.name }} says:</p>
            <p class="block static text-justify text-xs sm:text-sm lg:text-lg p-3">{{ content }}</p>

            <ul class="list-none p-3">
                <li><a href="#" data-meerkat-form="reply" data-meerkat-reply-to="{{ id }}">Reply</a></li>
            </ul>
        </div>
    </li>
    {{ /comments }}
</ul>
{{ /date_groups }}


{{ /meerkat:responses }}
```

### Example of Grouped Paginated Rendering

```html
{{ meerkat:responses paginate="true" pageby="instance1" limit="2" group_by_date="Y m, d" }}


{{ date_groups }}
<h2>Group: {{ date_group }}</h2>

<ul>
    {{ comments }}
    <li class="relative flex w-full flow-root">
        <img src="https://picsum.photos/id/684/600/400" alt=""
             class="h-12 w-12 mt-1 border-gray-500 rounded-full border-4">

        <div class="relative">
            <p class="block font-bold p-3 lg:text-lg">{{ author.name }} says:</p>
            <p class="block static text-justify text-xs sm:text-sm lg:text-lg p-3">{{ content }}</p>

            <ul class="list-none p-3">
                <li><a href="#" data-meerkat-form="reply" data-meerkat-reply-to="{{ id }}">Reply</a></li>
            </ul>
        </div>
    </li>
    {{ /comments }}
</ul>
{{ /date_groups }}

{{ paginate.auto_links }}

{{ /meerkat:responses }}

```

However, the new recursive engine will now automatically wrap the `<ul>{{ *recursive comments* }}</ul>` template part in the appropriate `if` check if it is found to be missing.

## Core

- [x] Hook up Comment/Thread Driver dependencies in Statamic Addon 
- [x] Remove Direct Dependencies
- [ ] Storage Indexes
  - [x] Thread Index
  - [x] Thread Hierarchy Index
  - [x] Comment Structure Index
  - [ ] Automatic Index Management
  - [ ] Command Line Utility to Rebuild Indexes
- [ ] Comment hierarchy
  - [x] Resolve Ancestors
  - [x] Resolve Descendents
  - [x] Resolve Direct Ancestor
  - [x] Resolve Direct Child, if any
  - [] Resolve Participants
- [x] Data Queries
  - [x] Consistent Data Converters
  - [x] Dynamic Sorting Predicate Builder
  - [x] Integration with Filtering System (including custom filters)
  - [x] Create bridge to convert legacy parameter types to query expressions
  - [x] Provide fluent query builder
  - [x] Support for arbitrary grouping mechanisms
  - [x] Support for arbitrary collection types and names
  - [x] Typed DataSet Support
    - [x] DatasetContract
    - [x] GroupedDatasetContract
    - [x] PagedDatasetContract
    - [x] PagedGroupedDatasetContract
- [x] Comment Instance
  - [x] Refactor away from Submission emulated behavior of Statamic 2 plugin
    - [x] Must maintain 100% compatibility with the abillity to define arbitrary data points (some in-the-wild examples are comment_tz, comment_time, etc.)
  - [x] Deferred Content (only fetch from disk if being filtered, displayed, or used in some way)
  - [x] Pre-host spam and published checks (we should be able to filter spam/published without invoking the YAML parser performance hit)
  - [x] Pre-host identity negotiation (who left the content?)
  - [x] Pre-host transient identity discovery (were they authenticated?)
  - [x] Pre-host ID resolution.
  - [x] Pre Host Internals
    - [x] INTERNAL_PATH
    - [x] INTERNAL_RESPONSE
    - [x] INTERNAL_RESPONSE_PATH
    - [x] INTERNAL_RESPONSE_ID
    - [x] INTERNAL_RESPONSE_CONTEXT
    - [x] INTERNAL_RESPONSE_HAS_REPLIES
- [x] Comment Structure Migrator
  - [x] Provide easy-to-use Artisan command
- [x] Comment Manager
  - [x] Get Comments for Thread ID (Must be memory efficient to avoid comment bombs; i.e., when scanning for comment "prototypes", we should never load all the content of the file)
  - [x] Get Replies for Comment ID
  - [x] Get Ancestors for Comment ID
  - [x] Get Descendents for Comment ID
  - [x] Get Ancestor Paths for Comment ID
  - [x] Get Descendent Paths for Comment ID
  - [x] Get Structured Attributes (migrator blocked)
  - [x] Deferred Parsing of Structued Data at Run-Time (only resolve structured data when its going to be used)
  - [x] setCommentContent($content) Method
  - [x] removeDataAttribute($attributeName) Method
  - [x] Save Structured Data (migrator blocked)
- [x] Context Resolver
- [x] Thread "Tasks" System
  - [x] Update Legacy Soft Deletes to New Format Automatically
- [x] Thread Manager (previously known as "Streams" in Meerkat)
  - [x] getAllThreads
  - [x] getAllThreadIds
  - [x] existsForContext
  - [x] getAllComments
  - [x] getAllCommentsById
  - [x] findById
  - [x] save
  - [x] determineVirtualPathById
  - [x] delete
  - [x] deleteById
  - [x] softDelete
  - [x] softDeleteById
  - [x] removeById
  - [x] moveThread
  - [x] restoreThread
- [x] Thread Action Hooks
  - [x] Thread Resolving
  - [x] Thread Removing
  - [x] Thread Removed
  - [x] Thread Soft Deleted
  - [x] Thread Creating
  - [x] Thread Restoring
  - [x] Thread Restored
  - [x] Thread Removing
  - [x] Thread Removed
- [x] Comment Manager
- [x] Identity Manager
- [x] Spam Guards
- [x] Resolve Meerkat Content Directory
- [x] Resolve Meerkat Content(s)
- [x] Set Configuration from Statamic Install
- [x] Migrate Permissions to Core
- [x] Refactor Core Permissions to use Meerkat Core Identity Manager
- [x] Memory-efficient method to retrieve comment meta data from file driver
- [x] Comment Change Tracking
  - [x] Track Comment Changes
  - [x] Allow Restoring to a Previous Comment State
  - [x] Allow Purging of Historical Change Sets
  - [x] Allow Disabling of Change Tracking via Configuration
## Generators (Testing)

- [x] Thread Generator from Current Contexts
- [x] Comment Generator for Threads - Current goal is to have _really good_ out of box performance for ~1,000 comments per thread before adding indexing and cache mechanisms

## HTTP APIs

- [ ] Theme: update (scaffolded)
- [ ] Theme: delete (scaffolded)
- [ ] Migration of CP APIs as needed
- [x] Error Logs (Control Panel & Super User)

## Meerkat Addon API

- [ ] Avatar Drivers (Gravatar, Letters, etc.)
- [ ] Provide Façade(s) for Laravel Developers
- [ ] Thread Lifecycle Hooks
 - [x] Thread Context Resolving - Developers can now intercept a thread's context resolution and augment the data that is returned
- [ ] Meerkat Lifecycle Hooks
  - [ ] Comment Action Hooks
    - [ ] Collecting/Retrieving (to be raised when constructing an instance of `Comment`)
    - [x] Soft Deleted
    - [x] Restoring
    - [x] Creating
    - [x] Created
    - [x] Editing
    - [x] Edited
    - [x] Replying
    - [x] Replied
    - [x] Marking as Spam
    - [x] Marked as Spam
    - [x] Marking as Ham
    - [x] Marked as Ham
    - [x] Approving
    - [x] Approved
    - [x] Unapproving
    - [x] Unapproved

**Comment by JohnathonKoster** [comment]
Quick sneak peak of some of performance gains (still needs some work) and Artisan features coming in Meerkat for Statamic 3!

![meerkat2_stats_sneakpeak](https://user-images.githubusercontent.com/5232890/87881388-93458f00-c9be-11ea-9a83-23d51acf817e.png)

**Comment by schmidtflo** [comment]
Hey, I'm really looking forward using Meerkat in Statamic 3! Can you give a insight when it's basically ready for a first test? I'm currently moving all my posts from my old blog by hand into the new Statamic version, so I would need just the basic feature set at first :-)

**Comment by JohnathonKoster** [comment]
@schmidtflo Hoping to have early alpha builds out by the end of August. The main hold ups at the moment are some issues I'm running into with the ability to update comment data without issues, and a basic Control Panel integration.

I am planning on having the save issues and some other Core items completed by the end of this weekend to focus on an initial Control Panel view. After that open-alpha/developer previews will start and last as long as it's needed.

I am very excited about that stage; and here are some screenshots of it running in the Cool Writings starter kit:

![threads_flat](https://user-images.githubusercontent.com/5232890/90959295-c9fc4280-e45f-11ea-9ba5-d9d915870660.png)
![threads_grouped](https://user-images.githubusercontent.com/5232890/90959297-ca94d900-e45f-11ea-907d-e7a162258e50.png)
![threads_grouped_paginated](https://user-images.githubusercontent.com/5232890/90959299-ca94d900-e45f-11ea-87eb-29881a8c9cb3.png)
![threads_nested](https://user-images.githubusercontent.com/5232890/90959300-ca94d900-e45f-11ea-855f-833f616179c3.png)
![threads_paginated](https://user-images.githubusercontent.com/5232890/90959301-ca94d900-e45f-11ea-8322-637ee6156d55.png)

**Comment by JohnathonKoster** [comment]
@schmidtflo 
Things are now in beta! You can find more at https://statamic.com/addons/stillat/meerkat-statamic-3 or the new website https://meerkatcomments.com/
