### ISSUE TITLE
Wrong comments count.

### ISSUE THREAD

**Issue by peimn** [Stillat/meerkat-v1hub#3]
Leave some comments on contents, then go to control panel and open an entry which has not any comment, go to comments tab and click on "Approved (0)"  then click "All", now the count of comments is showing the wrong number (shows total number of all comments on website).

Latest Meerkat.

**Comment by JohnathonKoster** [comment]
Thanks; I will look into it!

**Comment by JohnathonKoster** [comment]
Traced to recursive comment-node traversal issues. Updating metric reporting to use a flat-list to avoid.
