### ISSUE TITLE
Meerkat 1.5.x Error after Statamic update to 2.11.9

### ISSUE THREAD

**Issue by ghost** [Stillat/meerkat-v1hub#5]
I updated Statamic to 2.11.9 today and after got this error message:

`FatalErrorException in MeerkatTags.php line 18:
Statamic\Addons\Collection\CollectionTags and Statamic\Addons\Meerkat\Helpers\CollectionTagHelpers define the same property ($paginated) in the composition of Statamic\Addons\Meerkat\MeerkatTags. However, the definition differs and is considered incompatible. Class was composed`

I'm running PHP 7.3.2.

Will there be a fix for that issue? 

Is there any update on Meerkat 2? 

Best regards

Mike

**Comment by crisfeim** [comment]
Same issue here. Replacing the properties worked for me. I've attached the file with the replacements i made if you want to give it a try (rename it to .php and place it the Meerkat > Helpers folder )

[CollectionTagHelpers.txt](https://github.com/Stillat/meerka-v1hub/files/2921657/CollectionTagHelpers.txt)

**Comment by ghost** [comment]
Hi @crisrojas, 

I did the same and fixed it on my own. It's pretty hard to reach out to the plugin owner. I hope he can officially fix the problems soon.

**Comment by JohnathonKoster** [comment]
@mikewink  @crisrojas  Issue is fixed/tested with Meerkat 1.5.3 (available in the Statamic Marketplace). If you purchased license keys from https://bag.stillat.com/ email/message me and I can get them converted into marketplace licenses for you :)

There are a number of items planned for Meerkat 2; this development will start heavily when Statamic 3 drops.
