### ISSUE TITLE
Wrong route for form edit

### ISSUE THREAD

**Issue by nightillusions** [Stillat/meerkat-v1hub#6]
**Versions:**
- Statamic v2.11.12
- Meerkat v1.5.3

**Step to reproduce:**

1. Fresh install of Meerkat
2. Go to "Comments" (/cp/addons/meerkat?source=cp-nav&filter=all)
3. Click on "Configure"
4. Redirect to `/cp/forms/Meerkat/edit`
5. Error shown:
```
ErrorException in 8e5d255073152589b67d0a05cdcf364e line 6:
Call to a member function title() on null (View: /statamic/resources/views/forms/edit.blade.php)
```
```
FatalThrowableError in 8e5d255073152589b67d0a05cdcf364e line 6:
Call to a member function title() on null
```

**Fix:**
`/site/addons/Meerkat/resources/views/streams/stream.blade.php`
on line 27
```
                @can('super')
                    <a href="{{ route('form.edit', ['form' => 'Meerkat']) }}" class="btn">{{ meerkat_trans('actions.configure') }}</a>
                @endcan
```
Replace  `['form' => 'Meerkat']` with `['form' => 'meerkat']`

Greetings

**Comment by JohnathonKoster** [comment]
Regression caused when field formset files were renamed to lowercase.
