### ISSUE TITLE
Meerkat 2.0 Feature Requests

### ISSUE THREAD

**Issue by JohnathonKoster** [Stillat/meerkat-v1hub#9]
Hi all! Let's use this issue/card to discuss Meerkat 2.0 feature requests and platform requirements. Development of Meerkat 2.x will begin when Statamic 3.x betas start to ship.

Here is the list of tasks for Meerkat 2:

* Feature parity with Meerkat 1.x
* Improved stability and compatibility with multiple Statamic versions
* Improved installation and upgrade experience

Please comment with your thoughts, opinions, and ideas!

**Comment by nightillusions** [comment]
One feature I would like to have native is to send messages on new comments (E-mail, Slack,...) to site admins. Maybe also to comment creator on answers

**Comment by JohnathonKoster** [comment]
> One feature I would like to have native is to send messages on new comments (E-mail, Slack,...) to site admins. Maybe also to comment creator on answers

V1 supports e-mail messaging to admin's through Statamic's core Forms API/Control panel interface. I will def. look into augmenting their capabilities for Slack, and other communication platforms.

**Comment by JohnathonKoster** [comment]
@nightillusions Meerkat version 1.5.5 now supports email sending (utilizing Statamic's form configuration) as well as any other addon that handles Statamic's form submission event. This is now available in the Statamic Marketplace :)

Edit: There was a bug that prevented it from working correctly before, but that has been resolved for the latest Statamic version(s)

**Comment by jeremydouglas** [comment]
Not sure if this is in Meerkat 1, but allowing members to subscribe to comments on a post by email is something I would use.

**Comment by JohnathonKoster** [comment]
All ideas here were kept in mind while building out the base of Meerkat 2 for Statamic 3; not everything is built into the core, but the ground work is there :)

All further discussion should happen here: https://github.com/Stillat/meerkat-statamic3/issues
